version: '3.10'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-model-api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - ../../models:/models
    networks:
      - app-network

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-web-app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
